# -----------------------------------------------------------------------------
# config.yaml — CoSMIC Coaching Writer Configuration
# -----------------------------------------------------------------------------
# Defines global runtime parameters for:
#   - LLM model selection
#   - RAG (retrieval-augmented generation) behavior
#   - Embedding model
#   - Coaching tone and constraints
# -----------------------------------------------------------------------------

llm_name: "ollama:qwen3:4b"

rag:
  topk: 5                    # Number of top retrieved documents to use
  retrieve_score_threshold: 0.7
  vector_db_path: "database/vector_db"
  update_threshold: 0.98     # Re-index threshold for document updates

embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
device: "cpu"

coach:
  max_new_tokens: 512
  style: "supportive, concise, academically rigorous"